In [77]:
import pandas as p
df1 = p.read_csv('charging_stations.csv')
print(df1.head())
df1.info()
df1.describe()
df1.duplicated(subset='station_id')
# save CSV (UTF-8)
df1.to_csv('data_processed/charging_stations.csv', index=False, encoding='utf-8')

  station_id       city  avg_charge_time_mins  daily_sessions  uptime_percent  \
0      CS001  Bangalore                    44             127            95.9
1      CS002      Delhi                    41             110            97.4
2      CS003    Kolkata                    49              89            95.4
3      CS004      Delhi                    40             137            90.9
4      CS005      Delhi                    47             144            91.1

   cost_per_kWh
0         12.23
1         13.47
2         11.63
3          9.22
4         11.74
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   station_id            50 non-null     object
 1   city                  50 non-null     object
 2   avg_charge_time_mins  50 non-null     int64
 3   daily_sessions        50 non-null     int64
 4   uptime_percent        50 non-null     float64
 5   cost_per_kWh          50 non-null     float64
dtypes: float64(2), int64(2), object(2)
memory usage: 2.5+ KB

In [78]:
df2 = p.read_csv('customers.csv')
print(df2.head())
print()
df2.info()
print()
df2.describe()
df2['signup_date'].unique()

#Converting data type 
df2['signup_date'] = p.to_datetime(df2['signup_date'])
df2.info()

#Creating Year, Quarter, Month Columns from signup_date Column
df2['Year'] = df2['signup_date'].dt.year
df2['QTR'] = df2['signup_date'].dt.quarter
df2['Month'] = df2['signup_date'].dt.month
df2['Month_Name'] = df2['signup_date'].dt.month_name()
df2.head(10)
# save CSV (UTF-8)
df2.to_csv('data_processed/customers.csv', index=False, encoding='utf-8')

  customer_id             name gender  age       city signup_date
0      C00001     Jayan Grover      F   27  Bangalore  2025-10-13
1      C00002    Gatik Acharya      M   41    Kolkata  2025-11-03
2      C00003    Jayan Shanker  Other   33    Kolkata  2024-04-20
3      C00004  Miraya Seshadri  Other   20  Bangalore  2025-09-29
4      C00005   Kabir Sundaram      F   30    Chennai  2025-08-20

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  2000 non-null   object
 1   name         2000 non-null   object
 2   gender       2000 non-null   object
 3   age          2000 non-null   int64
 4   city         2000 non-null   object
 5   signup_date  2000 non-null   object
dtypes: int64(1), object(5)
memory usage: 93.9+ KB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  2000 non-null   object
 1   name         2000 non-null   object
 2   gender       2000 non-null   object
 3   age          2000 non-null   int64
 4   city         2000 non-null   object
 5   signup_date  2000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 93.9+ KB

In [79]:
df3 = p.read_csv('drivers.csv')
print(df3.head())
df3.info()
df3['join_date'] = p.to_datetime(df3['join_date'])
df3.info()

#Creating Year, Quarter, Month Columns from join_date Column
df3['Year'] = df3['join_date'].dt.year
df3['QTR'] = df3['join_date'].dt.quarter
df3['Month'] = df3['join_date'].dt.month
df3['Month_Name'] = df3['join_date'].dt.month_name()
df3.head(10)
# save CSV (UTF-8)
df3.to_csv('data_processed/drivers.csv', index=False, encoding='utf-8')

  driver_id                 name       city gender vehicle_id   join_date  \
0     D0001        Lakshit Boase  Bangalore      F      V0080  2024-08-27
1     D0002          Nehmat Bedi      Delhi      F      V0119  2024-10-16
2     D0003        Nishith Kumer      Delhi      F      V0159  2024-08-13
3     D0004  Vaibhav Subramaniam       Pune      F      V0096  2023-12-07
4     D0005          Farhan Devi       Pune      F      V0047  2024-10-14

   avg_rating
0        4.89
1        4.71
2        4.28
3        4.65
4        4.60
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   driver_id   300 non-null    object
 1   name        300 non-null    object
 2   city        300 non-null    object
 3   gender      300 non-null    object
 4   vehicle_id  300 non-null    object
 5   join_date   300 non-null    object
 6   avg_rating  300 non-null    float64
dtypes: float64(1), object(6)
memory usage: 16.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   driver_id   300 non-null    object
 1   name        300 non-null    object
 2   city        300 non-null    object
 3   gender      300 non-null    object
 4   vehicle_id  300 non-null    object
 5   join_date   300 non-null    datetime64[ns]
 6   avg_rating  300 non-null    float64
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 16.5+ KB

In [80]:
df4 = p.read_csv('payments.csv')
print(df4.head())
df4.info()
df4.describe()
# save CSV (UTF-8)
df4.to_csv('data_processed/payments.csv', index=False, encoding='utf-8')

  payment_id  ride_id  mode  amount   status  tip_amount
0    P000001  R000001   UPI  190.92  Success          10
1    P000002  R000002  Cash   45.20  Success           5
2    P000003  R000003   UPI  108.92  Success          10
3    P000004  R000004   UPI   96.88  Success           0
4    P000005  R000005  Card   68.36  Success           0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   payment_id  5000 non-null   object
 1   ride_id     5000 non-null   object
 2   mode        5000 non-null   object
 3   amount      5000 non-null   float64
 4   status      5000 non-null   object
 5   tip_amount  5000 non-null   int64
dtypes: float64(1), int64(1), object(4)
memory usage: 234.5+ KB

In [81]:
df5 = p.read_csv('rides.csv')
print(df5.head())
df5.info()
df5.describe()
df5['start_time'] = p.to_datetime(df5['start_time'])
df5['end_time'] = p.to_datetime(df5['end_time'])
df5.info()
df5.head(10)
# save CSV (UTF-8)
df5.to_csv('data_processed/rides.csv', index=False, encoding='utf-8')

   ride_id driver_id customer_id vehicle_id           start_time  \
0  R000001     D0208      C00927      V0024  2025-04-16 11:09:00
1  R000002     D0151      C01575      V0270  2024-05-21 08:23:00
2  R000003     D0076      C00974      V0230  2025-08-19 07:14:00
3  R000004     D0079      C01219      V0087  2024-09-19 09:05:00
4  R000005     D0104      C00888      V0290  2025-08-07 12:36:00

              end_time  distance_km  fare_amount payment_id  rating       city
0  2025-04-16 11:48:00        10.91       180.92    P000001     4.6  Hyderabad
1  2024-05-21 08:32:00         1.90        40.20    P000002     4.2       Pune
2  2025-08-19 07:40:00         4.91        98.92    P000003     4.5  Bangalore
3  2024-09-19 09:31:00         4.74        96.88    P000004     4.6  Hyderabad
4  2025-08-07 13:03:00         5.42        68.36    P000005     5.0  Ahmedabad
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ride_id      5000 non-null   object
 1   driver_id    5000 non-null   object
 2   customer_id  5000 non-null   object
 3   vehicle_id   5000 non-null   object
 4   start_time   5000 non-null   object
 5   end_time     5000 non-null   object
 6   distance_km  5000 non-null   float64
 7   fare_amount  5000 non-null   float64
 8   payment_id   5000 non-null   object
 9   rating       5000 non-null   float64
 10  city         5000 non-null   object
dtypes: float64(3), object(8)
memory usage: 429.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ride_id      5000 non-null   object
 1   driver_id    5000 non-null   object
 2   customer_id  5000 non-null   object
 3   vehicle_id   5000 non-null   object
 4   start_time   5000 non-null   datetime64[ns]
 5   end_time     5000 non-null   datetime64[ns]
 6   distance_km  5000 non-null   float64
 7   fare_amount  5000 non-null   float64
 8   payment_id   5000 non-null   object
 9   rating       5000 non-null   float64
 10  city         5000 non-null   object
dtypes: datetime64[ns](2), float64(3), object(6)
memory usage: 429.8+ KB

In [82]:
df6 = p.read_csv('vehicles.csv')
print(df6.head())
df6.info()
# save CSV (UTF-8)
df6.to_csv('data_processed/vehicles.csv', index=False, encoding='utf-8')

  vehicle_id          model    brand   type  battery_capacity_kWh  range_km  \
0      V0001   Tata Nano EV     Tata   Auto                   9.2       118
1      V0002   Hyundai Kona  Hyundai  Sedan                  40.5       504
2      V0003     Ather 450X    Ather   Bike                   2.9        73
3      V0004   Tata Nano EV     Tata   Auto                   9.7       127
4      V0005  Tata Nexon EV     Tata    SUV                  29.5       325

   purchase_year
0           2022
1           2023
2           2023
3           2022
4           2022
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   vehicle_id            300 non-null    object
 1   model                 300 non-null    object
 2   brand                 300 non-null    object
 3   type                  300 non-null    object
 4   battery_capacity_kWh  300 non-null    float64
 5   range_km              300 non-null    int64
 6   purchase_year         300 non-null    int64
dtypes: float64(1), int64(2), object(4)
memory usage: 16.5+ KB

In [94]:
import os
import pandas as pd

DATA_DIR = r"C:\Users\style\EV_Ride_Sharing_Full_Dataset\data_processed"

# only CSVs
csv_files = [f for f in os.listdir(DATA_DIR) if f.lower().endswith('.csv')]
print("CSV files found:", csv_files)

for fname in csv_files:
    path = os.path.join(DATA_DIR, fname)
    df = pd.read_csv(path)
    print(fname, "rows:", len(df))
    display(df.head(3))

CSV files found: ['charging_stations.csv', 'customers.csv', 'drivers.csv', 'payments.csv', 'rides.csv', 'vehicles.csv']
charging_stations.csv rows: 50

,station_id,city,avg_charge_time_mins,daily_sessions,uptime_percent,cost_per_kWh
0,CS001,Bangalore,44,127,95.9,12.23
1,CS002,Delhi,41,110,97.4,13.47
2,CS003,Kolkata,49,89,95.4,11.63

customers.csv rows: 2000

,customer_id,name,gender,age,city,signup_date,Year,QTR,Month,Month_Name
0,C00001,Jayan Grover,F,27,Bangalore,2025-10-13,2025,4,10,October
1,C00002,Gatik Acharya,M,41,Kolkata,2025-11-03,2025,4,11,November
2,C00003,Jayan Shanker,Other,33,Kolkata,2024-04-20,2024,2,4,April

drivers.csv rows: 300

,driver_id,name,city,gender,vehicle_id,join_date,avg_rating,Year,QTR,Month,Month_Name
0,D0001,Lakshit Boase,Bangalore,F,V0080,2024-08-27,4.89,2024,3,8,August
1,D0002,Nehmat Bedi,Delhi,F,V0119,2024-10-16,4.71,2024,4,10,October
2,D0003,Nishith Kumer,Delhi,F,V0159,2024-08-13,4.28,2024,3,8,August

payments.csv rows: 5000

  payment_id  ride_id  mode  amount   status  tip_amount
0    P000001  R000001   UPI  190.92  Success          10
1    P000002  R000002  Cash   45.20  Success           5
2    P000003  R000003   UPI  108.92  Success          10

rides.csv rows: 5000

,ride_id,driver_id,customer_id,vehicle_id,start_time,end_time,distance_km,fare_amount,payment_id,rating,city
0,R000001,D0208,C00927,V0024,2025-04-16 11:09:00,2025-04-16 11:48:00,10.91,180.92,P000001,4.6,Hyderabad
1,R000002,D0151,C01575,V0270,2024-05-21 08:23:00,2024-05-21 08:32:00,1.90,40.20,P000002,4.2,Pune
2,R000003,D0076,C00974,V0230,2025-08-19 07:14:00,2025-08-19 07:40:00,4.91,98.92,P000003,4.5,Bangalore

vehicles.csv rows: 300

,vehicle_id,model,brand,type,battery_capacity_kWh,range_km,purchase_year
0,V0001,Tata Nano EV,Tata,Auto,9.2,118,2022
1,V0002,Hyundai Kona,Hyundai,Sedan,40.5,504,2023
2,V0003,Ather 450X,Ather,Bike,2.9,73,2023

In [95]:
import os
import pandas as pd

# Folder where your cleaned data lives
DATA_DIR = r"C:\Users\style\EV_Ride_Sharing_Full_Dataset\data_processed"

# Expected record counts (approximate)
expected_counts = {
    'rides_clean.csv': 5000,
    'drivers_clean.csv': 300,
    'vehicles_clean.csv': 300,
    'customers_clean.csv': 2000,
    'payments_clean.csv': 5000,
    'charging_stations_clean.csv': 50
}

# Only include .csv files
csv_files = [f for f in os.listdir(DATA_DIR) if f.lower().endswith('.csv')]
print("CSV files found:", csv_files)
print()

# Loop through each file and verify
for fname in csv_files:
    path = os.path.join(DATA_DIR, fname)
    df = pd.read_csv(path)
    rows = len(df)
    expected = expected_counts.get(fname)
    
    # Check and print summary
    if expected:
        if rows >= expected * 0.95:  # allow ±5% margin
            print(f"✅ {fname}: {rows:,} rows (as expected)")
        else:
            print(f"⚠️ {fname}: {rows:,} rows — expected around {expected:,}")
    else:
        print(f"ℹ️ {fname}: {rows:,} rows (no expected count defined)")
    
    # Show a preview
    display(df.head(3))

print("\n✅ Verification complete — all datasets successfully loaded.")

CSV files found: ['charging_stations.csv', 'customers.csv', 'drivers.csv', 'payments.csv', 'rides.csv', 'vehicles.csv']

ℹ️ charging_stations.csv: 50 rows (no expected count defined)

,station_id,city,avg_charge_time_mins,daily_sessions,uptime_percent,cost_per_kWh
0,CS001,Bangalore,44,127,95.9,12.23
1,CS002,Delhi,41,110,97.4,13.47
2,CS003,Kolkata,49,89,95.4,11.63

ℹ️ customers.csv: 2,000 rows (no expected count defined)

,customer_id,name,gender,age,city,signup_date,Year,QTR,Month,Month_Name
0,C00001,Jayan Grover,F,27,Bangalore,2025-10-13,2025,4,10,October
1,C00002,Gatik Acharya,M,41,Kolkata,2025-11-03,2025,4,11,November
2,C00003,Jayan Shanker,Other,33,Kolkata,2024-04-20,2024,2,4,April

ℹ️ drivers.csv: 300 rows (no expected count defined)

,driver_id,name,city,gender,vehicle_id,join_date,avg_rating,Year,QTR,Month,Month_Name
0,D0001,Lakshit Boase,Bangalore,F,V0080,2024-08-27,4.89,2024,3,8,August
1,D0002,Nehmat Bedi,Delhi,F,V0119,2024-10-16,4.71,2024,4,10,October
2,D0003,Nishith Kumer,Delhi,F,V0159,2024-08-13,4.28,2024,3,8,August

ℹ️ payments.csv: 5,000 rows (no expected count defined)

  payment_id  ride_id  mode  amount   status  tip_amount
0    P000001  R000001   UPI  190.92  Success          10
1    P000002  R000002  Cash   45.20  Success           5
2    P000003  R000003   UPI  108.92  Success          10

ℹ️ rides.csv: 5,000 rows (no expected count defined)

,ride_id,driver_id,customer_id,vehicle_id,start_time,end_time,distance_km,fare_amount,payment_id,rating,city
0,R000001,D0208,C00927,V0024,2025-04-16 11:09:00,2025-04-16 11:48:00,10.91,180.92,P000001,4.6,Hyderabad
1,R000002,D0151,C01575,V0270,2024-05-21 08:23:00,2024-05-21 08:32:00,1.90,40.20,P000002,4.2,Pune
2,R000003,D0076,C00974,V0230,2025-08-19 07:14:00,2025-08-19 07:40:00,4.91,98.92,P000003,4.5,Bangalore

ℹ️ vehicles.csv: 300 rows (no expected count defined)

,vehicle_id,model,brand,type,battery_capacity_kWh,range_km,purchase_year
0,V0001,Tata Nano EV,Tata,Auto,9.2,118,2022
1,V0002,Hyundai Kona,Hyundai,Sedan,40.5,504,2023
2,V0003,Ather 450X,Ather,Bike,2.9,73,2023

✅ Verification complete — all datasets successfully loaded.

In [3]:
!pip install pyodbc

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyodbc in c:\users\style\appdata\roaming\python\python312\site-packages (5.3.0)

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pyodbc
print(pyodbc.drivers())

['SQL Server', 'Oracle in OraDB19Home1', 'Oracle in OraDB19Home2', 'Oracle in OraDB19Home3', 'SQL Server Native Client RDA 11.0', 'ODBC Driver 17 for SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [6]:
import pyodbc

server = r'LAPTOP-IG80BF3U\ABSERVERPBI'   # Your actual SQL Server instance
database = 'EV_Ride_Sharing'               # Your database name

conn_str = (
    "DRIVER={ODBC Driver 17 for SQL Server};"
    f"SERVER={server};DATABASE={database};"
    "Trusted_Connection=yes;"
)

# Create connection
cnxn = pyodbc.connect(conn_str)
cursor = cnxn.cursor()

# Test the connection
user = cursor.execute("SELECT SUSER_SNAME()").fetchval()
db = cursor.execute("SELECT DB_NAME()").fetchval()
print(f"✅ Connected successfully as: {user}")
print(f"📂 Current Database: {db}")

cursor.close()
cnxn.close()

✅ Connected successfully as: LAPTOP-IG80BF3U\style
📂 Current Database: EV_Ride_Sharing

In [14]:
import os
import pandas as pd
import pyodbc

# --- Connection details (you already confirmed these) ---
server = r'LAPTOP-IG80BF3U\ABSERVERPBI'
database = 'EV_Ride_Sharing'

conn_str = (
    "DRIVER={ODBC Driver 17 for SQL Server};"
    f"SERVER={server};DATABASE={database};"
    "Trusted_Connection=yes;Encrypt=no"
)

# Connect to SQL Server
cnxn = pyodbc.connect(conn_str)
cursor = cnxn.cursor()
cursor.fast_executemany = True
print("✅ SQL Server connection established.")

# --- Folder containing your cleaned CSV files ---
DATA_DIR = r"C:\Users\style\EV_Ride_Sharing_Full_Dataset\data_processed"

# Map CSV filenames → SQL table names
table_map = {
    'drivers.csv': 'drivers',
    'vehicles.csv': 'vehicles',
    'customers.csv': 'customers',
    'payments.csv': 'payments',
    'charging_stations.csv': 'charging_stations',
    'rides.csv': 'rides'
}


# --- Load each CSV into its corresponding SQL table ---
for fname, table in table_map.items():
    path = os.path.join(DATA_DIR, fname)
    
    if not os.path.exists(path):
        print(f"⚠️ Skipping {fname} — file not found.")
        continue

    print(f"\n📦 Loading {fname} → [{table}] ...")

    # Read CSV into DataFrame
    df = pd.read_csv(path)
    rows = len(df)

    # Build SQL insert statement dynamically
    cols = list(df.columns)
    col_names = ",".join([f"[{c}]" for c in cols])
    placeholders = ",".join(["?"] * len(cols))
    sql = f"INSERT INTO dbo.{table} ({col_names}) VALUES ({placeholders})"

    try:
        cursor.executemany(sql, df.itertuples(index=False, name=None))
        cnxn.commit()
        print(f"✅ Loaded {rows:,} rows into [{table}] successfully.")
    except Exception as e:
        print(f"❌ Error loading [{table}]: {e}")
        cnxn.rollback()

cursor.close()
cnxn.close()
print("\n🎉 All CSVs processed — data successfully loaded into SQL Server!")

✅ SQL Server connection established.

📦 Loading drivers.csv → [drivers] ...
✅ Loaded 300 rows into [drivers] successfully.

📦 Loading vehicles.csv → [vehicles] ...
✅ Loaded 300 rows into [vehicles] successfully.

📦 Loading customers.csv → [customers] ...
✅ Loaded 2,000 rows into [customers] successfully.

📦 Loading payments.csv → [payments] ...
✅ Loaded 5,000 rows into [payments] successfully.

📦 Loading charging_stations.csv → [charging_stations] ...
✅ Loaded 50 rows into [charging_stations] successfully.

📦 Loading rides.csv → [rides] ...
✅ Loaded 5,000 rows into [rides] successfully.

🎉 All CSVs processed — data successfully loaded into SQL Server!

In [10]:
import os

# Check what files exist in your given folder
DATA_DIR = r"C:\Users\style\EV_Ride_Sharing_Full_Dataset\data_processed"
print("Checking path:", DATA_DIR)

if os.path.exists(DATA_DIR):
    print("\nFiles in folder:")
    print(os.listdir(DATA_DIR))
else:
    print("❌ Folder not found — check the correct path in File Explorer.")

Checking path: C:\Users\style\EV_Ride_Sharing_Full_Dataset\data_processed

Files in folder:
['.ipynb_checkpoints', 'charging_stations.csv', 'customers.csv', 'drivers.csv', 'payments.csv', 'rides.csv', 'vehicles.csv']